// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwWoNb3Upq7NfDUeZ9TA9fQp8rQwPgYQk',
    appId: '1:494080873125:web:8f5dc383b766bd89c0334c',
    messagingSenderId: '494080873125',
    projectId: 'foirebase-memo',
    authDomain: 'foirebase-memo.firebaseapp.com',
    storageBucket: 'foirebase-memo.appspot.com',
    measurementId: 'G-GQRPM6Y2EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz781pNuNZszKiqQWE6HLRWqeB7TJ8O-8',
    appId: '1:494080873125:android:8b6303e8c8d9eedec0334c',
    messagingSenderId: '494080873125',
    projectId: 'foirebase-memo',
    storageBucket: 'foirebase-memo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZdHkEIhtsKLD2HCXLhcxE0E7LHjjQwmM',
    appId: '1:494080873125:ios:bab11fcb4c20985bc0334c',
    messagingSenderId: '494080873125',
    projectId: 'foirebase-memo',
    storageBucket: 'foirebase-memo.appspot.com',
    iosClientId: '494080873125-tufvpflmgfs98hddcqn9k634ribm7ljg.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZdHkEIhtsKLD2HCXLhcxE0E7LHjjQwmM',
    appId: '1:494080873125:ios:bab11fcb4c20985bc0334c',
    messagingSenderId: '494080873125',
    projectId: 'foirebase-memo',
    storageBucket: 'foirebase-memo.appspot.com',
    iosClientId: '494080873125-tufvpflmgfs98hddcqn9k634ribm7ljg.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp1',
  );
}
